// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwoydnecyomusvgombil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3b3lkbmVjeW9tdXN2Z29tYmlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0Mzk0MDksImV4cCI6MjA2OTAxNTQwOX0.8YA_AjZ2VVJG3JJkKJ95V0d4XYEC8d3auEK3AXpSz6c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});